version: '2'

services:
  ul-vbentity:
    build: 
      context: .
      args: 
        BAGET_API_KEY: ${BAGET_API_KEY}
        BAGET_URL: ${BAGET_URL}
    mem_limit: 1G
    networks:
      - ul-docker

networks:
  ul-docker:
    external: true
